In [ ]:
%pip install --upgrade datascience

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 727 kB 5.1 MB/s 
     |████████████████████████████████| 95 kB 4.4 MB/s 
  Created wheel for datascience: filename=datascience-0.17.5-py3-none-any.whl size=732545 sha256=329c43aa1dbf338dd3cd17962d7147008b83b9fdd21ca19673088d22f80550fa
  Stored in directory: /root/.cache/pip/wheels/e4/88/ba/14ba45035fe366e3c9d3395404885c6348bb8e656da107e822
Successfully built datascience
  Attempting uninstall: folium
    Found existing installation: folium 0.8.3
    Uninstalling folium-0.8.3:
      Successfully uninstalled folium-0.8.3
  Attempting uninstall: datascience
    Found existing installation: datascience 0.10.6
    Uninstalling datascience-0.10.6:
      Successfully uninstalled datascience-0.10.6


In [ ]:
%pip install small-text[transformers]==1.0.0b3  # use "small-text" without "[transformers]" if you want to work on the CPU only

# additional dependencies for this example
%pip install datasets matplotlib seaborn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 122 kB 5.2 MB/s 
     |████████████████████████████████| 4.4 MB 33.6 MB/s 
     |████████████████████████████████| 6.6 MB 67.2 MB/s 
     |████████████████████████████████| 101 kB 11.9 MB/s 
     |████████████████████████████████| 596 kB 76.9 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 362 kB 5.1 MB/s 
     |████████████████████████████████| 140 kB 55.3 MB/s 
     |████████████████████████████████| 212 kB 62.7 MB/s 
     |████████████████████████████████| 1.1 MB 45.8 MB/s 
     |████████████████████████████████| 127 kB 67.0 MB/s 
     |████████████████████████████████| 144 kB 53.6 MB/s 
     |███████████

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#找到包的位置，进行修改;!!每次重启colab都需要更改
import small_text
print(small_text.__file__)

/usr/local/lib/python3.7/dist-packages/small_text/__init__.py


## 导入第三方库

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from ast import literal_eval
from sklearn.cluster import DBSCAN

## 导入数据

In [ ]:
### 需要注意，这里的数据的ids2就是已经经过某种变换得到的文本句向量
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/情感轨道打分数据/demo_all_new_cluster_0608_新.csv')
df

Unnamed: 0                                             nopunc  \
0               0  一九六九年 四月 一日 报告 四月 十四日 通过 林彪 同志 们 中国共产党第九次全国代表大...   
1               1  三月份 月度 进出口 规模 创新 高 本报 北京 月 日 讯 记者 杜 海涛 报道 海关 最...   
2               2  上海 石油化工 总厂 靠 智力开发 起飞 本报记者 吴复民 红玛瑙 似的 运转 指示灯 蓦然...   
3               3  下关市 举行宴会 欢迎 廖承志 副委员长 一行 据 新华社 下关 五月 九日 电以 廖承志 ...   
4               4  世界 人民 和平 大会 记事 袁水拍 和平 运动 的 老战士 们 像 意大利 多尼 尼 教授...   
...           ...                                                ...   
29834       29934  马巍年 中国 电影 市场 春节 档 创造 了 新 的 纪录 得益于 多部 本土 贺岁 新片 ...   
29835       29935  马本斋 抗日战争 时期 在 华北平原 上 活跃 着 一支 以 回民 兄弟 为主 组成 的 抗...   
29836       29936  黄国越 强烈 谴责 美机 轰炸 北方 的 强盗 罪行 强调 越南 南北方 人民 决心 战胜 ...   
29837       29937  黑脸 琵鹭 请 让 我 来 关心 你 本报记者 钟嘉 严寒 挡不住 野生动物 保护者 们 的...   
29838       29938  齐晖 回到 正常 轨道 据 新华社 北京 月 日电 记者 杨 金志 张薇 好运 北京 中国 ...   

                                                   score  \
0      [0.03160141239429076, -0.04957382465915392, -0...   
1      [0.04964349019864235, 0.10936169526692757, 0.2...   
2      [0.08104942550423407, 0.13883518507868425, 0.0...   
3      [-0.0023794892647571574, 0.07346247383454761, ...   
4      [-0.02011695787621593, 0.055439573707884174, 0...   
...                                                  ...   
29834  [0.01587601603410936, 0.03764139184979351, 0.0...   
29835  [0.09842621728702378, 0.012364107498986858, 0....   
29836  [0.008617210604590055, -0.010541628111763762, ...   
29837  [-0.13765827980058357, 0.21133572460376754, -0...   
29838  [-0.09221178504979227, 0.04223222883799189, 0....   

                                                    ids2  label  cluster_db  
0      [0.00048361006, 0.0007332484, 0.0007011582, 0....      6           0  
1      [0.00047500295, 0.0006828284, 0.0005490131, 0....      5           0  
2      [0.00047698742, 0.00074580207, 0.00063491095, ...      6           0  
3      [0.00051801256, 0.000820847, 0.00079044106, 0....      1           0  
4      [0.00050378207, 0.0008450187, 0.000899082, 0.0...      4           0  
...                                                  ...    ...         ...  
29834  [0.00047775434, 0.00074808166, 0.00064183446, ...      6           0  
29835  [0.00050345284, 0.0008048199, 0.00074749044, 0...      5           0  
29836  [0.00050013704, 0.00077063765, 0.0007441554, 0...      5           0  
29837  [0.00048234698, 0.0007665205, 0.0007214704, 0....      5           0  
29838  [0.0004863677, 0.0007542312, 0.00069294375, 0....      5           0  

[29839 rows x 6 columns]

In [ ]:
df['Unnamed: 0'] = df.index
df

Unnamed: 0                                             nopunc  \
0               0  一九六九年 四月 一日 报告 四月 十四日 通过 林彪 同志 们 中国共产党第九次全国代表大...   
1               1  三月份 月度 进出口 规模 创新 高 本报 北京 月 日 讯 记者 杜 海涛 报道 海关 最...   
2               2  上海 石油化工 总厂 靠 智力开发 起飞 本报记者 吴复民 红玛瑙 似的 运转 指示灯 蓦然...   
3               3  下关市 举行宴会 欢迎 廖承志 副委员长 一行 据 新华社 下关 五月 九日 电以 廖承志 ...   
4               4  世界 人民 和平 大会 记事 袁水拍 和平 运动 的 老战士 们 像 意大利 多尼 尼 教授...   
...           ...                                                ...   
29834       29834  马巍年 中国 电影 市场 春节 档 创造 了 新 的 纪录 得益于 多部 本土 贺岁 新片 ...   
29835       29835  马本斋 抗日战争 时期 在 华北平原 上 活跃 着 一支 以 回民 兄弟 为主 组成 的 抗...   
29836       29836  黄国越 强烈 谴责 美机 轰炸 北方 的 强盗 罪行 强调 越南 南北方 人民 决心 战胜 ...   
29837       29837  黑脸 琵鹭 请 让 我 来 关心 你 本报记者 钟嘉 严寒 挡不住 野生动物 保护者 们 的...   
29838       29838  齐晖 回到 正常 轨道 据 新华社 北京 月 日电 记者 杨 金志 张薇 好运 北京 中国 ...   

                                                   score  \
0      [0.03160141239429076, -0.04957382465915392, -0...   
1      [0.04964349019864235, 0.10936169526692757, 0.2...   
2      [0.08104942550423407, 0.13883518507868425, 0.0...   
3      [-0.0023794892647571574, 0.07346247383454761, ...   
4      [-0.02011695787621593, 0.055439573707884174, 0...   
...                                                  ...   
29834  [0.01587601603410936, 0.03764139184979351, 0.0...   
29835  [0.09842621728702378, 0.012364107498986858, 0....   
29836  [0.008617210604590055, -0.010541628111763762, ...   
29837  [-0.13765827980058357, 0.21133572460376754, -0...   
29838  [-0.09221178504979227, 0.04223222883799189, 0....   

                                                    ids2  label  cluster_db  
0      [0.00048361006, 0.0007332484, 0.0007011582, 0....      6           0  
1      [0.00047500295, 0.0006828284, 0.0005490131, 0....      5           0  
2      [0.00047698742, 0.00074580207, 0.00063491095, ...      6           0  
3      [0.00051801256, 0.000820847, 0.00079044106, 0....      1           0  
4      [0.00050378207, 0.0008450187, 0.000899082, 0.0...      4           0  
...                                                  ...    ...         ...  
29834  [0.00047775434, 0.00074808166, 0.00064183446, ...      6           0  
29835  [0.00050345284, 0.0008048199, 0.00074749044, 0...      5           0  
29836  [0.00050013704, 0.00077063765, 0.0007441554, 0...      5           0  
29837  [0.00048234698, 0.0007665205, 0.0007214704, 0....      5           0  
29838  [0.0004863677, 0.0007542312, 0.00069294375, 0....      5           0  

[29839 rows x 6 columns]

In [ ]:
#将句向量提取出来（这里便是ids2这一列），用于后面的步骤
ls = []
for i in range(len(df)):
    tem = literal_eval(df.ids2[i]) # 将字符串的数组转成python列表数据
    ls.append(tem)
dff = pd.DataFrame(ls)
dff

0         1         2         3         4         5         6    \
0      0.000484  0.000733  0.000701  0.002016  0.001329  0.000929  0.002143   
1      0.000475  0.000683  0.000549  0.002061  0.001817  0.000918  0.002148   
2      0.000477  0.000746  0.000635  0.002000  0.001514  0.000946  0.002126   
3      0.000518  0.000821  0.000790  0.001887  0.001318  0.001035  0.001876   
4      0.000504  0.000845  0.000899  0.001963  0.001269  0.001024  0.002039   
...         ...       ...       ...       ...       ...       ...       ...   
29834  0.000478  0.000748  0.000642  0.001978  0.001529  0.000947  0.002017   
29835  0.000503  0.000805  0.000747  0.001873  0.001443  0.001001  0.001894   
29836  0.000500  0.000771  0.000744  0.001929  0.001412  0.001010  0.002016   
29837  0.000482  0.000767  0.000721  0.002008  0.001392  0.000981  0.002107   
29838  0.000486  0.000754  0.000693  0.001993  0.001455  0.000968  0.002101   

            7         8         9    ...       758       759       760  \
0      0.001592  0.000828  0.000412  ...  0.002268  0.001648  0.001569   
1      0.001542  0.000718  0.000407  ...  0.002259  0.001345  0.002061   
2      0.001487  0.000789  0.000411  ...  0.002230  0.001587  0.001830   
3      0.001553  0.000983  0.000419  ...  0.002220  0.001644  0.001348   
4      0.001491  0.001141  0.000418  ...  0.002136  0.001717  0.001283   
...         ...       ...       ...  ...       ...       ...       ...   
29834  0.001476  0.000793  0.000411  ...  0.002300  0.001581  0.001719   
29835  0.001467  0.000960  0.000417  ...  0.002204  0.001685  0.001493   
29836  0.001580  0.000931  0.000416  ...  0.002341  0.001540  0.001437   
29837  0.001477  0.000902  0.000413  ...  0.002217  0.001646  0.001594   
29838  0.001533  0.000833  0.000413  ...  0.002282  0.001509  0.001576   

            761       762       763       764       765       766       767  
0      0.002422  0.000741  0.001834  0.002357  0.000573  0.000685  0.002327  
1      0.002351  0.000619  0.001609  0.002325  0.000482  0.000689  0.002292  
2      0.002364  0.000727  0.001779  0.002323  0.000531  0.000709  0.002356  
3      0.002282  0.000872  0.001888  0.002318  0.000601  0.000756  0.002184  
4      0.002378  0.000834  0.002007  0.002229  0.000650  0.000741  0.002197  
...         ...       ...       ...       ...       ...       ...       ...  
29834  0.002368  0.000702  0.001809  0.002396  0.000533  0.000710  0.002383  
29835  0.002311  0.000838  0.001911  0.002321  0.000558  0.000755  0.002262  
29836  0.002377  0.000815  0.001896  0.002434  0.000574  0.000717  0.002253  
29837  0.002427  0.000757  0.001954  0.002302  0.000564  0.000720  0.002374  
29838  0.002368  0.000742  0.001860  0.002352  0.000558  0.000705  0.002332  

[29839 rows x 768 columns]

## 使用DBSCAN算法，去除噪声点

In [ ]:
db = DBSCAN(eps=5e-4, min_samples=2).fit(dff)#1e-3 # 调用第三方库实现的DBSCAN方法，eps表示距离，这个距离需要根据情况设定


labels = db.labels_
df['cluster_db'] = labels 

#得到的聚类结果进行排序，标签为-1表示为离群点噪声
df.sort_values('cluster_db')

Unnamed: 0                                             nopunc  \
0               0  一九六九年 四月 一日 报告 四月 十四日 通过 林彪 同志 们 中国共产党第九次全国代表大...   
19592       19592  据 新华社 北京 月 日电 国务院 副 总理 万里 今天上午 在 人民大会堂 会见 以 日本...   
19591       19591  据 新华社 北京 十月 十五日 电 日本 驻 中国 大使 吉田健 三 今晚 在 寓所 举行宴...   
19590       19590  据 新华社 北京 十二月 十日 电 记者 黄彩虹 通讯员 胡春华 国外 医疗 仪器设备 技术...   
19589       19589  据 新华社 东京 电据 日本 信用调查 机构 日前 发表 的 一份 统计 报告 今年 月 至...   
...           ...                                                ...   
28997       28997  本报 北京 月 日电 记者 李文云 吴绮敏 外交部 日 举行 中外记者 吹风会 外交部 副 ...   
28563       28563  著名 鱼类 学家 孟庆闻 教授 谈 我国 水产业 发展前景 徐英杰 迟 英杰 在 远望 楼 ...   
27567       27567  著名 鱼类 学家 孟庆闻 教授 谈 我国 水产业 发展前景 徐英杰 迟 英杰 在 远望 楼 ...   
27815       27815  新华社 东京 一九七四年 六月 十八日 电 日本政府 六月 十七日 要求 苏联 停止 在 堪...   
28277       28277  新华社 东京 一九七四年 六月 十八日 电 日本政府 六月 十七日 要求 苏联 停止 在 堪...   

                                                   score  \
0      [0.03160141239429076, -0.04957382465915392, -0...   
19592  [-0.2946468089584601, 0.08830235788129075, 0.1...   
19591  [-0.1290616648618951, 0.10533843642809314, 0.0...   
19590  [0.15014390004830971, 0.22377742851138913, 0.1...   
19589  [-0.47261307711745054, -0.07315147894879392, -...   
...                                                  ...   
28997  [0.032606233904425734, 0.008416538815304417, -...   
28563  [-0.0720049155745836, 0.09290163974264994, 0.0...   
27567  [-0.0720049155745836, 0.09290163974264994, 0.0...   
27815  [-0.3443089928906562, -0.01922738699390133, 0....   
28277  [-0.3443089928906562, -0.01922738699390133, 0....   

                                                    ids2  label  cluster_db  
0      [0.00048361006, 0.0007332484, 0.0007011582, 0....      6          -1  
19592  [0.0004781373, 0.0007617718, 0.0006507814, 0.0...      2          -1  
19591  [0.00045537445, 0.0006888852, 0.00057867746, 0...      0          -1  
19590  [0.0004609971, 0.00072615175, 0.00048810348, 0...      2          -1  
19589  [0.00045329062, 0.0007066977, 0.00064801157, 0...      1          -1  
...                                                  ...    ...         ...  
28997  [0.00047977886, 0.0007588326, 0.0008040693, 0....      4         755  
28563  [0.0006016785, 0.0008502666, 0.00066138094, 0....      5         756  
27567  [0.0006016785, 0.0008502666, 0.00066138094, 0....      5         756  
27815  [0.00045155807, 0.00069860846, 0.0006180139, 0...      3         757  
28277  [0.00045155807, 0.00069860846, 0.0006180139, 0...      3         757  

[29839 rows x 6 columns]

In [ ]:
#去除离群点
df2 = df.sort_values('cluster_db')
df2 = df2[df2['cluster_db'] >= 0] #label为-1表示离群点（噪声），我们要做的就是去除噪声
df2.index = range(len(df2))
df2

Unnamed: 0                                             nopunc  \
0              2  上海 石油化工 总厂 靠 智力开发 起飞 本报记者 吴复民 红玛瑙 似的 运转 指示灯 蓦然...   
1           7960  记 韩国 围棋 名将 徐奉洙 本报记者 李长云 月 日 徐奉洙 在 中日 韩三国 围棋 擂台...   
2              5  世界 人民 团结起来 反对 美帝国主义 反对 殖民主义 争取 民族 独立 的 运动 和 争取...   
3          27115  从 六月 二十日 到 七月 四日 各国 人民 在 反对 企图 破坏 和平 民族 独立 和 社...   
4              9  中国 女单 选手 仅 一人 晋级 据 新华社 东京 月 日电 记者 韩 建军 日本 羽毛球 ...   
...          ...                                                ...   
1806       28997  本报 北京 月 日电 记者 李文云 吴绮敏 外交部 日 举行 中外记者 吹风会 外交部 副 ...   
1807       28563  著名 鱼类 学家 孟庆闻 教授 谈 我国 水产业 发展前景 徐英杰 迟 英杰 在 远望 楼 ...   
1808       27567  著名 鱼类 学家 孟庆闻 教授 谈 我国 水产业 发展前景 徐英杰 迟 英杰 在 远望 楼 ...   
1809       27815  新华社 东京 一九七四年 六月 十八日 电 日本政府 六月 十七日 要求 苏联 停止 在 堪...   
1810       28277  新华社 东京 一九七四年 六月 十八日 电 日本政府 六月 十七日 要求 苏联 停止 在 堪...   

                                                  score  \
0     [0.08104942550423407, 0.13883518507868425, 0.0...   
1     [0.20235320639983423, 0.05430732601529806, 0.0...   
2     [0.09878971320208893, -0.006174163308367696, 0...   
3     [-0.018328547181785067, -0.055746163160883926,...   
4     [0.10083148548593293, -0.013307861172860588, 0...   
...                                                 ...   
1806  [0.032606233904425734, 0.008416538815304417, -...   
1807  [-0.0720049155745836, 0.09290163974264994, 0.0...   
1808  [-0.0720049155745836, 0.09290163974264994, 0.0...   
1809  [-0.3443089928906562, -0.01922738699390133, 0....   
1810  [-0.3443089928906562, -0.01922738699390133, 0....   

                                                   ids2  label  cluster_db  
0     [0.00047698742, 0.00074580207, 0.00063491095, ...      6           0  
1     [0.0004788125, 0.000757477, 0.0006434765, 0.00...      4           0  
2     [0.00051358563, 0.00078221323, 0.00074385345, ...      1           1  
3     [0.0005097126, 0.00078712957, 0.0007424802, 0....      5           1  
4     [0.0005099016, 0.00080418563, 0.00077287393, 0...      4           2  
...                                                 ...    ...         ...  
1806  [0.00047977886, 0.0007588326, 0.0008040693, 0....      4         755  
1807  [0.0006016785, 0.0008502666, 0.00066138094, 0....      5         756  
1808  [0.0006016785, 0.0008502666, 0.00066138094, 0....      5         756  
1809  [0.00045155807, 0.00069860846, 0.0006180139, 0...      3         757  
1810  [0.00045155807, 0.00069860846, 0.0006180139, 0...      3         757  

[1811 rows x 6 columns]

## 开始Core-set算法，得到重要数据

### 导入第三方包

In [ ]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from sklearn.metrics import pairwise_distances
import abc
from sklearn.neighbors import KNeighborsClassifier

### 定义方法

In [ ]:
class SamplingMethod(object):
    __metaclass__ = abc.ABCMeta

    @abc.abstractmethod
    def __init__(self, X, y, seed, **kwargs):
        self.X = X
        self.y = y
        self.seed = seed

    def flatten_X(self):
        shape = self.X.shape
        flat_X = self.X
        if len(shape) > 2:
              flat_X = np.reshape(self.X, (shape[0],np.product(shape[1:])))
        return flat_X


    @abc.abstractmethod
    def select_batch_(self):
        return

    def select_batch(self, **kwargs):
        return self.select_batch_(**kwargs)

    def to_dict(self):
        return None

In [ ]:
class kCenterGreedy(SamplingMethod):

    def __init__(self, X, y, seed, metric='euclidean'):
        self.X = X
        self.y = y
        self.flat_X = self.flatten_X()
        self.name = 'kcenter'
        self.features = self.flat_X
        self.metric = metric
        self.min_distances = None
        self.n_obs = self.X.shape[0]
        self.already_selected = []
        
    def update_distances(self, cluster_centers, only_new=True, reset_dist=False):
        """Update min distances given cluster centers.

        Args:
          cluster_centers: indices of cluster centers
          only_new: only calculate distance for newly selected points and update
            min_distances.
          rest_dist: whether to reset min_distances.
        """

        if reset_dist:
            self.min_distances = None
        if only_new:
            cluster_centers = [d for d in cluster_centers
                             if d not in self.already_selected]
        if cluster_centers:
          # Update min_distances for all examples given new cluster center.
            x = self.features[cluster_centers]
            dist = pairwise_distances(self.features, x, metric=self.metric)

            if self.min_distances is None:
                self.min_distances = np.min(dist, axis=1).reshape(-1,1)
            else:
                self.min_distances = np.minimum(self.min_distances, dist)
                
    def select_batch_(self, model, already_selected, N, **kwargs):
        """
        Diversity promoting active learning method that greedily forms a batch
        to minimize the maximum distance to a cluster center among all unlabeled
        datapoints.

        Args:
          model: model with scikit-like API with decision_function implemented
          already_selected: index of datapoints already selected
          N: batch size

        Returns:
          indices of points selected to minimize distance to cluster centers
        """

        try:
            # Assumes that the transform function takes in original data and not
            # flattened data.
            print('Getting transformed features...')
            # self.features = model.transform(self.X)
            self.features = self.X
            print('Calculating distances...')
            self.update_distances(already_selected, only_new=False, reset_dist=True)
        except:
            print('Using flat_X as features.')
            self.update_distances(already_selected, only_new=True, reset_dist=False)

        new_batch = []

        for _ in range(N):
            if self.already_selected is None:
                # Initialize centers with a randomly selected datapoint
                print("random")
                ind = np.random.choice(np.arange(self.n_obs))
            else:
                print("normal")
                ind = np.argmax(self.min_distances)
            # New examples should not be in already selected since those points
            # should have min_distance of zero to a cluster center.
            print(ind)
            assert ind not in already_selected

            #print([ind])
            self.update_distances([ind], only_new=True, reset_dist=False)
            new_batch.append(ind)
        print('Maximum distance from cluster centers is %0.5f'
                % max(self.min_distances))


        self.already_selected = already_selected

        return new_batch

In [ ]:
#将去除了离群点后的文本句向量提取出来，进行core-set距离的计算
cd = []
for i in range(len(df2)):
    cd.append(literal_eval(df2.ids2[i]))

df_X = np.array(cd)
print(df_X)
df_X.shape

[[0.00047699 0.0007458  0.00063491 ... 0.00053116 0.00070947 0.00235615]
 [0.00047881 0.00075748 0.00064348 ... 0.00053033 0.00072087 0.00231723]
 [0.00051359 0.00078221 0.00074385 ... 0.0005676  0.00072948 0.00212638]
 ...
 [0.00060168 0.00085027 0.00066138 ... 0.00054601 0.00083574 0.00185535]
 [0.00045156 0.00069861 0.00061801 ... 0.00057417 0.00062783 0.0024312 ]
 [0.00045156 0.00069861 0.00061801 ... 0.00057417 0.00062783 0.0024312 ]]


(1811, 768)

In [ ]:
df_Y = np.ones(df_X.shape[0])
print(df_Y)
df_Y.shape

[1. 1. 1. ... 1. 1. 1.]


(1811,)

In [ ]:
clf = KNeighborsClassifier()
ind = np.random.choice(np.arange(df_X.shape[0]))#np.random.choice
df_X=np.delete(df_X,ind,0)
df_Y=np.delete(df_Y,[0],0)
kc = kCenterGreedy(df_X, df_Y, 0)

kc.update_distances([ind], only_new=True, reset_dist=False)

ass = []
ass.append(ind)
for i in range(20):
    asl = kc.select_batch_(clf, ass, 50)
    ass = ass + asl

df1 = df2.iloc[ass, :]
df1

910
[[0.00047699 0.0007458  0.00063491 ... 0.00053116 0.00070947 0.00235615]
 [0.00047881 0.00075748 0.00064348 ... 0.00053033 0.00072087 0.00231723]
 [0.00051359 0.00078221 0.00074385 ... 0.0005676  0.00072948 0.00212638]
 ...
 [0.00060168 0.00085027 0.00066138 ... 0.00054601 0.00083574 0.00185535]
 [0.00045156 0.00069861 0.00061801 ... 0.00057417 0.00062783 0.0024312 ]
 [0.00045156 0.00069861 0.00061801 ... 0.00057417 0.00062783 0.0024312 ]]
Getting transformed features...
Calculating distances...
normal
1440
normal
1743
normal
917
normal
1123
normal
350
normal
1507
normal
438
normal
1099
normal
1745
normal
216
normal
1662
normal
67
normal
1551
normal
1247
normal
1641
normal
1714
normal
457
normal
1623
normal
461
normal
1138
normal
1300
normal
1501
normal
1458
normal
1483
normal
881
normal
1438
normal
867
normal
1749
normal
1055
normal
1521
normal
1485
normal
695
normal
1057
normal
578
normal
477
normal
1383
normal
104
normal
875
normal
1217
normal
1411
normal
1211
normal
1170
normal

Unnamed: 0                                             nopunc  \
910        23505  记刘军 吴文凯 和 叶钊颖 大器晚成 的 刘军 岁 的 刘军 是 第一次 参加 汤姆斯杯 大...   
1440       21970  据 新华社 华盛顿 月 日电 美国国防部 今天 宣布 它 已 结束 对 苏联 击落 的 南朝...   
1743       23192  撰文 本报记者 王科 摄影 本报记者 徐烨 进入 月份 京城 方便面 市场 广告战 烽烟 滚...   
917        29688  欧盟 坚持 为 发达国家 设定 减排 目标 的 立场 新华社 印度尼西亚 巴厘岛 月 日电 ...   
1123        9324  本报讯 由 中国教育电视台 组织 制作 并 选送 的 学前教育 节目 水 荣获 第二十届 日...   
...          ...                                                ...   
369         2024  第十四届 莫斯科 国际 电影节 侧记 沈修 苏联 的 雅恩 科夫斯基 和 日本 的 栗 原小...   
1336       12912  新华社 马尼拉 月 日电 记者 熊昌义 第十三届 亚洲 青年 男子篮球 锦标赛 今天 在 这...   
102          382  张振亚 月 日 是 纽约证券交易所 的 大喜 日子 因为 年前 的 今天 即 年月日 正好 ...   
166         1755  邓副 总理 访日 促进 中日 睦邻友好 关系 发展 叶 委员长 主持会议 并 讲 了 话 他...   
1358       16579  领导 干部 怎能 合伙 谋私 渠县 某厂 招收 一百多名 新 工人 尽 开后门 北京日报 北...   

                                                  score  \
910   [0.08363340129086125, 0.04479033488382278, 0.0...   
1440  [0.5536343671567495, -0.3376107637535376, -0.0...   
1743  [0.09387951755382687, 0.13408453164495399, 0.0...   
917   [-0.00732369080907392, -0.14751790610805166, 0...   
1123  [0.08824024279760381, 0.039049141967970345, 0....   
...                                                 ...   
369   [0.07276833256286924, 0.01581582972578923, 0.0...   
1336  [0.08450791474521945, -0.12306511657334365, 0....   
102   [0.02015805061404206, -0.015027266015661062, -...   
166   [0.008709656389503023, -0.095272663210376, 0.0...   
1358  [-0.04580647257159044, 0.15011507198983245, -0...   

                                                   ids2  label  cluster_db  
910   [0.0004774135, 0.00073742867, 0.00066535483, 0...      3         331  
1440  [0.0004929455, 0.0008045098, 0.00082463457, 0....      3         582  
1743  [0.0004873177, 0.00075037306, 0.00065624755, 0...      6         725  
917   [0.00048176898, 0.0007440749, 0.0007212356, 0....      6         332  
1123  [0.00048173248, 0.00072168716, 0.00061232643, ...      0         429  
...                                                 ...    ...         ...  
369   [0.0004793009, 0.0007403568, 0.0006345119, 0.0...      6         111  
1336  [0.00045358817, 0.00067737064, 0.00059455435, ...      6         531  
102   [0.00049992284, 0.00079386006, 0.0007559553, 0...      3          25  
166   [0.00048407333, 0.0007408759, 0.00070472143, 0...      0          32  
1358  [0.00046629758, 0.0007040896, 0.0006444942, 0....      6         542  

[1001 rows x 6 columns]

In [ ]:
df1.index = range(len(df1))
df1

Unnamed: 0                                             nopunc  \
0          23505  记刘军 吴文凯 和 叶钊颖 大器晚成 的 刘军 岁 的 刘军 是 第一次 参加 汤姆斯杯 大...   
1          21970  据 新华社 华盛顿 月 日电 美国国防部 今天 宣布 它 已 结束 对 苏联 击落 的 南朝...   
2          23192  撰文 本报记者 王科 摄影 本报记者 徐烨 进入 月份 京城 方便面 市场 广告战 烽烟 滚...   
3          29688  欧盟 坚持 为 发达国家 设定 减排 目标 的 立场 新华社 印度尼西亚 巴厘岛 月 日电 ...   
4           9324  本报讯 由 中国教育电视台 组织 制作 并 选送 的 学前教育 节目 水 荣获 第二十届 日...   
...          ...                                                ...   
996         2024  第十四届 莫斯科 国际 电影节 侧记 沈修 苏联 的 雅恩 科夫斯基 和 日本 的 栗 原小...   
997        12912  新华社 马尼拉 月 日电 记者 熊昌义 第十三届 亚洲 青年 男子篮球 锦标赛 今天 在 这...   
998          382  张振亚 月 日 是 纽约证券交易所 的 大喜 日子 因为 年前 的 今天 即 年月日 正好 ...   
999         1755  邓副 总理 访日 促进 中日 睦邻友好 关系 发展 叶 委员长 主持会议 并 讲 了 话 他...   
1000       16579  领导 干部 怎能 合伙 谋私 渠县 某厂 招收 一百多名 新 工人 尽 开后门 北京日报 北...   

                                                  score  \
0     [0.08363340129086125, 0.04479033488382278, 0.0...   
1     [0.5536343671567495, -0.3376107637535376, -0.0...   
2     [0.09387951755382687, 0.13408453164495399, 0.0...   
3     [-0.00732369080907392, -0.14751790610805166, 0...   
4     [0.08824024279760381, 0.039049141967970345, 0....   
...                                                 ...   
996   [0.07276833256286924, 0.01581582972578923, 0.0...   
997   [0.08450791474521945, -0.12306511657334365, 0....   
998   [0.02015805061404206, -0.015027266015661062, -...   
999   [0.008709656389503023, -0.095272663210376, 0.0...   
1000  [-0.04580647257159044, 0.15011507198983245, -0...   

                                                   ids2  label  cluster_db  
0     [0.0004774135, 0.00073742867, 0.00066535483, 0...      3         331  
1     [0.0004929455, 0.0008045098, 0.00082463457, 0....      3         582  
2     [0.0004873177, 0.00075037306, 0.00065624755, 0...      6         725  
3     [0.00048176898, 0.0007440749, 0.0007212356, 0....      6         332  
4     [0.00048173248, 0.00072168716, 0.00061232643, ...      0         429  
...                                                 ...    ...         ...  
996   [0.0004793009, 0.0007403568, 0.0006345119, 0.0...      6         111  
997   [0.00045358817, 0.00067737064, 0.00059455435, ...      6         531  
998   [0.00049992284, 0.00079386006, 0.0007559553, 0...      3          25  
999   [0.00048407333, 0.0007408759, 0.00070472143, 0...      0          32  
1000  [0.00046629758, 0.0007040896, 0.0006444942, 0....      6         542  

[1001 rows x 6 columns]

## uncertain

In [ ]:
import torch
# import numpy as np

seed = 2022
torch.manual_seed(seed)
np.random.seed(seed)

In [ ]:
df_train = df1.drop(columns=['Unnamed: 0','score','ids2','cluster_db'])
df_train

nopunc  label
0     记刘军 吴文凯 和 叶钊颖 大器晚成 的 刘军 岁 的 刘军 是 第一次 参加 汤姆斯杯 大...      3
1     据 新华社 华盛顿 月 日电 美国国防部 今天 宣布 它 已 结束 对 苏联 击落 的 南朝...      3
2     撰文 本报记者 王科 摄影 本报记者 徐烨 进入 月份 京城 方便面 市场 广告战 烽烟 滚...      6
3     欧盟 坚持 为 发达国家 设定 减排 目标 的 立场 新华社 印度尼西亚 巴厘岛 月 日电 ...      6
4     本报讯 由 中国教育电视台 组织 制作 并 选送 的 学前教育 节目 水 荣获 第二十届 日...      0
...                                                 ...    ...
996   第十四届 莫斯科 国际 电影节 侧记 沈修 苏联 的 雅恩 科夫斯基 和 日本 的 栗 原小...      6
997   新华社 马尼拉 月 日电 记者 熊昌义 第十三届 亚洲 青年 男子篮球 锦标赛 今天 在 这...      6
998   张振亚 月 日 是 纽约证券交易所 的 大喜 日子 因为 年前 的 今天 即 年月日 正好 ...      3
999   邓副 总理 访日 促进 中日 睦邻友好 关系 发展 叶 委员长 主持会议 并 讲 了 话 他...      0
1000  领导 干部 怎能 合伙 谋私 渠县 某厂 招收 一百多名 新 工人 尽 开后门 北京日报 北...      6

[1001 rows x 2 columns]

In [ ]:
df_train['label'] = 1
# df_train.rename(columns={'nopunc':'text'})
df_train.columns = ['text', 'label']
df_train

text  label
0     记刘军 吴文凯 和 叶钊颖 大器晚成 的 刘军 岁 的 刘军 是 第一次 参加 汤姆斯杯 大...      1
1     据 新华社 华盛顿 月 日电 美国国防部 今天 宣布 它 已 结束 对 苏联 击落 的 南朝...      1
2     撰文 本报记者 王科 摄影 本报记者 徐烨 进入 月份 京城 方便面 市场 广告战 烽烟 滚...      1
3     欧盟 坚持 为 发达国家 设定 减排 目标 的 立场 新华社 印度尼西亚 巴厘岛 月 日电 ...      1
4     本报讯 由 中国教育电视台 组织 制作 并 选送 的 学前教育 节目 水 荣获 第二十届 日...      1
...                                                 ...    ...
996   第十四届 莫斯科 国际 电影节 侧记 沈修 苏联 的 雅恩 科夫斯基 和 日本 的 栗 原小...      1
997   新华社 马尼拉 月 日电 记者 熊昌义 第十三届 亚洲 青年 男子篮球 锦标赛 今天 在 这...      1
998   张振亚 月 日 是 纽约证券交易所 的 大喜 日子 因为 年前 的 今天 即 年月日 正好 ...      1
999   邓副 总理 访日 促进 中日 睦邻友好 关系 发展 叶 委员长 主持会议 并 讲 了 话 他...      1
1000  领导 干部 怎能 合伙 谋私 渠县 某厂 招收 一百多名 新 工人 尽 开后门 北京日报 北...      1

[1001 rows x 2 columns]

### df_test的label是真实的标签,导入真实有标注的数据；用于初始化模型

In [ ]:
df_test = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dev_6_0_not_used.csv")
df_test

label                                               text
0       0  本报记者潘承凡几年前看过一则报道说是日本人研究改变西瓜的外形培育出方形西瓜以便搬运时码垛减少...
1       1  正当国人们为中国棋手在数届中日围棋擂台赛上的不断获胜而欣然不已的时候大家可能忽略了中方棋手在...
2       0  本报驻美国记者李博雅本报驻日本记者刘军国日前美国海军学会网站发表题为通过日本视角日本影院的二...
3       0  金熙德9月22日下午日本自民党总裁选举尘埃落地自民党干事长麻生太郎以绝对优势当选自民党总裁并...
4       0  本报东京7月3日电记者于青促进北方领土等问题解决特别措施法修正案3日上午在日本参议院获得全票...
5       0  关于民族独立问题的决议亚洲及太平洋区域和平会议坚信和平与民族独立是分不开的如果任何一国的领土...
6       1  铲除中日关系正常化的障碍新华社23日讯行将离开北京回国的日本社会党访华亲善使节团今晚举行临别...
7       0  访城南旧事作者林海音胞妹林燕珠石四维林燕珠是城南旧事的原作者台湾女作家林海音女士在祖国大陆上...
8       1  罗葆齐寒鸦惊啼枫红黯逝虽然时令还只是秋冬交替的时候但是由于不久前一次特大台风的侵袭日本九千万...
9       1  日本五十万人集会要求停止核扩军新华社东京10月24日电日本近畿地区群众约50万人今天在大阪举...
10      1  对身体不适的运动员可劝其退出比赛本报东京电记者孙东民报道日本排球协会2月20日做出决定为了早...
11      0  我国内地除云南外其他省区市部分地区及东海海域空气中检测出极微量放射性核素碘１３１不会对我国环...
12      1  为解决注射器针头的二次感染问题日本三光纯药公司最近研制出专门用于对用过的注射器针头进行灭菌的...
13      0  美国海外军事基地苑文在美帝国主义的全球侵略计划中建筑海外军事基地占着重要的地位根据美国官方消...
14      1  蒋元椿不久以前英国首相邱吉尔在伍德佛的演说中表明了他可以做一些反复无常背信弃义的事情的人他在...
15      1  国纪平近年来中日关系出现困难局面两国人民担忧国际社会关注今年3月31日中国国家主席胡锦涛在北...
16      1  朝鲜劳动新闻十二日发表评论敦促日本彻底放弃军国主义思维方式由政府出面承认过去所犯下的全部罪行...
17      1  首都集会支持朝日人民正义斗争邓小平陈毅康生等领导人和在京的朝鲜日本等国朋友出席刘宁一致开会词...
18      1  新华社28日讯据塔斯社27日报道不久前又有一批日本平民在苏联红十字会与红新月会联合会执行委员...
19      1  排除现代修正主义障碍赢得新胜利苏代表贩卖错误路线的修正主义面目被揭露新华社二十二日讯东京消息...

### 合并两个数据

In [ ]:
df_train = pd.concat([df_test, df_train])
df_train.index = range(len(df_train))
df_train

label                                               text
0         0  本报记者潘承凡几年前看过一则报道说是日本人研究改变西瓜的外形培育出方形西瓜以便搬运时码垛减少...
1         1  正当国人们为中国棋手在数届中日围棋擂台赛上的不断获胜而欣然不已的时候大家可能忽略了中方棋手在...
2         0  本报驻美国记者李博雅本报驻日本记者刘军国日前美国海军学会网站发表题为通过日本视角日本影院的二...
3         0  金熙德9月22日下午日本自民党总裁选举尘埃落地自民党干事长麻生太郎以绝对优势当选自民党总裁并...
4         0  本报东京7月3日电记者于青促进北方领土等问题解决特别措施法修正案3日上午在日本参议院获得全票...
...     ...                                                ...
1016      1  第十四届 莫斯科 国际 电影节 侧记 沈修 苏联 的 雅恩 科夫斯基 和 日本 的 栗 原小...
1017      1  新华社 马尼拉 月 日电 记者 熊昌义 第十三届 亚洲 青年 男子篮球 锦标赛 今天 在 这...
1018      1  张振亚 月 日 是 纽约证券交易所 的 大喜 日子 因为 年前 的 今天 即 年月日 正好 ...
1019      1  邓副 总理 访日 促进 中日 睦邻友好 关系 发展 叶 委员长 主持会议 并 讲 了 话 他...
1020      1  领导 干部 怎能 合伙 谋私 渠县 某厂 招收 一百多名 新 工人 尽 开后门 北京日报 北...

[1021 rows x 2 columns]

### 开始使用small text框架来搭建主动学习

In [ ]:
from transformers import AutoTokenizer, BertTokenizer

#导入我们之前已经训练了的模型
transformer_model_name = '/content/drive/MyDrive/train（result_6）'

tokenizer = BertTokenizer.from_pretrained(
    transformer_model_name
)

In [ ]:
from small_text.integrations.transformers.datasets import TransformersDataset


def get_transformers_dataset(tokenizer, data, labels, max_length=100):

    data_out = []

    for i, doc in enumerate(data):
        encoded_dict = tokenizer.encode_plus(
            doc,
            add_special_tokens=True,
            padding='max_length',
            max_length=max_length,
            return_attention_mask=True,
            return_tensors='pt',
            truncation='longest_first'
        )

        data_out.append((encoded_dict['input_ids'], encoded_dict['attention_mask'], labels[i]))

    return TransformersDataset(data_out)

train = get_transformers_dataset(tokenizer, df_train['text'], df_train['label'])
test = get_transformers_dataset(tokenizer, df_test['text'], df_test['label'])

##### 初始化框架

In [ ]:
from small_text.active_learner import PoolBasedActiveLearner

from small_text.initialization import random_initialization_balanced
from small_text.integrations.transformers import TransformerModelArguments
from small_text.integrations.transformers.classifiers.factories import TransformerBasedClassificationFactory
from small_text.query_strategies import PredictionEntropy, LeastConfidence
from small_text.integrations.transformers import TransformerModelArguments


num_classes = 2


# simulates an initial labeling to warm-start the active learning process
def initialize_active_learner(active_learner, y_train):
  
    # indices_initial = random_initialization_balanced(y_train, n_samples=20)
    indices_initial = range(20)
    print(indices_initial)
    active_learner.initialize_data(indices_initial, y_train[indices_initial])

    

    return indices_initial



transformer_model = TransformerModelArguments(transformer_model_name)
clf_factory = TransformerBasedClassificationFactory(transformer_model, 
                                                    num_classes, 
                                                    kwargs=dict({'device': 'cuda', 
                                                                 'mini_batch_size': 32,
                                                                 'class_weight': 'balanced'
                                                                }))
# query_strategy = PredictionEntropy()
query_strategy = LeastConfidence()

active_learner = PoolBasedActiveLearner(clf_factory, query_strategy, train)
indices_labeled = initialize_active_learner(active_learner, test.y)

range(0, 20)


##### 挑选文本

In [ ]:
from sklearn.metrics import accuracy_score


num_queries = 1


def evaluate(active_learner, train, test):
    y_pred = active_learner.classifier.predict(train)
    y_pred_test = active_learner.classifier.predict(test)
    
    test_acc = accuracy_score(y_pred_test, test.y)

    print('Train accuracy: {:.2f}'.format(accuracy_score(y_pred, train.y)))
    print('Test accuracy: {:.2f}'.format(test_acc))
    
    return test_acc


results = []
# results.append(evaluate(active_learner, train[indices_labeled], test))

    
for i in range(num_queries):
    # ...where each iteration consists of labelling 20 samples
    indices_queried = active_learner.query(num_samples=100)
    # print(indices_queried)
    results.append(indices_queried)
results[0]

array([  84,  608,  605,  600,  997,   25,  619,  574,  547,  544,  518,
        482,  449,  431,  725,  729,  419,  731,  410,  401,  394,  948,
        986, 1010,  371,  367,  324,  301,  286,  285,  866,   51,  871,
        880,  165,  163,  887,  150,  116,  106,  920, 1012,  772,  203,
        438,  541,  220,  649,  137,   69,  650,   29,  522,   21,  424,
        178,  264,  283,  676,  990,  741,  309,  972,  889,  308,  782,
        378,  615,  942,  279,  853,  722,  692,  844,  166,  921,  591,
        723,  448,  781,   85,  136,   71,  322,  727,  791,  255,   50,
        411,  555,  421,  263,  886,  806,  730,  966,  758,  505,  813,
        584])

In [ ]:
results1 = results[0] - 20 # 去掉初始化的前20条数据的标签带来的影响
results1#改index-20，自动缩回20位

array([ 64, 588, 585, 580, 977,   5, 599, 554, 527, 524, 498, 462, 429,
       411, 705, 709, 399, 711, 390, 381, 374, 928, 966, 990, 351, 347,
       304, 281, 266, 265, 846,  31, 851, 860, 145, 143, 867, 130,  96,
        86, 900, 992, 752, 183, 418, 521, 200, 629, 117,  49, 630,   9,
       502,   1, 404, 158, 244, 263, 656, 970, 721, 289, 952, 869, 288,
       762, 358, 595, 922, 259, 833, 702, 672, 824, 146, 901, 571, 703,
       428, 761,  65, 116,  51, 302, 707, 771, 235,  30, 391, 535, 401,
       243, 866, 786, 710, 946, 738, 485, 793, 564])

##### 得到筛选出来的数据

In [ ]:
df_al = df1.iloc[results1,:]
df_al

Unnamed: 0                                             nopunc  \
64          627  中国 射击队 总教练 张福 我国 射击 健儿 将 在 第十届 亚运会 上 参加 十五个 项目...   
588       11337  新华社 二十八日 讯 人大常委会 副委员长 郭沫若 今天上午 接见 了 以 羽根 荣一 为首...   
585       23153  我队 以三比 击败 西德 队据 新华社 卢布尔雅那 十七日 电 第二十八届 世界 乒乓球 锦...   
580       10930  本报记者 张志文 俞懿春 陈然 为期 两天 的 海洋 争端 解决 国际法 研讨会 月 日 在...   
977       15512  自杀 已 成为 导致 日本 国家 公务员 死亡 的 第二 大 杀手 这是 日本 人事 院对 ...   
..          ...                                                ...   
946       26878  本报记者 刘仲华 赵成 李锋曲 翔宇 月 日 上午 国家 主席 习近平 应邀出席 在 巴布亚...   
738        9349  本报记者 董洪亮 对 城乡 公办 小学 初中 实行 标准化 建设 这是 一个 重要 的 转折...   
485       27606  读 世界 园林 发展 概论 顾孟潮 当 中国 城市化 进程 空前 加速 许多 城市 把 建设...   
793       12773  张岂之 中国 社会 与 西方 文化 这是 一个 值得 研究 的 大 课题 吉林大学 宝成关 ...   
564       10294  新华社 北京 月 日电 中国国际贸易促进委员会 主任 王耀庭 今天 晚上 在 人民大会堂 举...   

                                                 score  \
64   [0.03281145845671823, -0.017463615092265815, -...   
588  [0.29648743156719615, 0.32386012075554876, 0.1...   
585  [-0.08030344345551038, 0.21372191697900417, -0...   
580  [0.0788475778882582, 0.04253629233204423, -0.0...   
977  [0.6826887657522522, -0.019241865926012004, 0....   
..                                                 ...   
946  [0.12110538111962316, -0.022792907240132772, 0...   
738  [0.07226085488766978, 0.0029080748422330265, -...   
485  [-0.006193101111100044, 0.07028134702255641, 0...   
793  [-0.01797448345831555, 0.014464619837890713, -...   
564  [0.3168834037615782, 0.20495370786071576, 0.12...   

                                                  ids2  label  cluster_db  
64   [0.0005638877, 0.0008500327, 0.00076776685, 0....      3          35  
588  [0.00044431264, 0.0006750464, 0.00052068726, 0...      2         490  
585  [0.00048121772, 0.0007018915, 0.0006014369, 0....      3         724  
580  [0.00047915656, 0.0007838957, 0.0007558922, 0....      0         479  
977  [0.0004532733, 0.0006645717, 0.00050379726, 0....      2         606  
..                                                 ...    ...         ...  
946  [0.0004722344, 0.0007055999, 0.0005853253, 0.0...      6         447  
738  [0.0004892258, 0.00074898213, 0.0007000114, 0....      4         273  
485  [0.0005228274, 0.00079466746, 0.0007758035, 0....      6         520  
793  [0.0004754468, 0.00074939243, 0.00064402405, 0...      6         122  
564  [0.00046765327, 0.00072707055, 0.00052286556, ...      4         457  

[100 rows x 6 columns]

##### 导入有监督训练的模型，进行轨道标签的修改

In [ ]:
import torch
from torch import nn

In [ ]:
class LSTM(nn.Module):

    def __init__(self, in_dim, hidden_dim, n_layer, n_class, bidirectional=False):
        super(LSTM, self).__init__()

        self.n_layer = n_layer
        self.hidden_dim = hidden_dim
        self.bidirectional = bidirectional

        self.lstm = nn.LSTM(in_dim, hidden_dim, n_layer, batch_first=True, bidirectional=bidirectional, dropout=0.1)
        self.softmax = nn.Softmax(dim=-1)

        if self.bidirectional:
            self.Classifier = nn.Linear(hidden_dim*2, n_class)

        else:
            self.Classifier = nn.Linear(hidden_dim, n_class)

    def forward(self, x):
        out, (hn, _) = self.lstm(x)
        if self.bidirectional:
            out = torch.hstack((hn[-2, :, :], hn[-1, :, :]))
        else:
            out = out[:, -1, :]
        out = self.Classifier(out)
        return self.softmax(out)

In [ ]:
model_old = torch.load("/content/drive/MyDrive/Colab Notebooks/lstm_all_3_第三轮增量学习fit后.pth")
# model = LSTM(100, 128, 2, 7, True)
model = LSTM(1, 128, 4, 7, True)
model.load_state_dict(model_old)

<All keys matched successfully>

In [ ]:
def getlabel(datax, model):
    datax = torch.tensor(datax).float()
    datax = datax.unsqueeze(-1)
    # print(datax.shape)
    # print(datax)
    pred = model(datax)
    print(pred.shape)
    print(pred.argmax(dim=-1))
    # print(datay)
    return pred.argmax(dim=-1)

###### 以下部分是进行dct变换，会和上面的代码有点重复，也可以通过索引的方式得到上面的dct变换结果，这里偷懒一下，重新计算

In [ ]:
from ast import literal_eval
from sklearn import preprocessing
from scipy.fftpack import dct
from scipy.fftpack import idct

In [ ]:
newdata_t_al=[]
min_max_scaler = preprocessing.MinMaxScaler()
for i in range(len(df_al)):
    tem=literal_eval(df_al.iloc[i, 2])#表示第i行，第2列（SCORE列）
    # tem=dct(tem, n=200)#dct变换
    tem=dct(tem)#dct变换
    tem = tem[:5]
    tem = tem/2
    tem = idct(tem, n=100)
    tem = tem/100
#     tem=standalize2(tem)#进行softmax标准化
    tem = min_max_scaler.fit_transform(tem.reshape(-1,1))
    newdata_t_al.append(tem.reshape(1,-1)[0])
#     newdata_t.append(tem)
newdata_t_al

[array([1.27243592e-01, 1.25546486e-01, 1.22204357e-01, 1.17320379e-01,
        1.11046834e-01, 1.03582201e-01, 9.51673312e-02, 8.60808136e-02,
        7.66335744e-02, 6.71628310e-02, 5.80254906e-02, 4.95911125e-02,
        4.22345558e-02, 3.63284404e-02, 3.22355534e-02, 3.03013347e-02,
        3.08465730e-02, 3.41604449e-02, 4.04940184e-02, 5.00543421e-02,
        6.29992259e-02, 7.94328119e-02, 9.94020202e-02, 1.22893941e-01,
        1.49834229e-01, 1.80086532e-01, 2.13452993e-01, 2.49675810e-01,
        2.88439852e-01, 3.29376298e-01, 3.72067256e-01, 4.16051280e-01,
        4.60829734e-01, 5.05873878e-01, 5.50632590e-01, 5.94540597e-01,
        6.37027088e-01, 6.77524572e-01, 7.15477847e-01, 7.50352930e-01,
        7.81645800e-01, 8.08890827e-01, 8.31668728e-01, 8.49613936e-01,
        8.62421240e-01, 8.69851597e-01, 8.71737008e-01, 8.67984363e-01,
        8.58578198e-01, 8.43582291e-01, 8.23140075e-01, 7.97473835e-01,
        7.66882693e-01, 7.31739403e-01, 6.92485987e-01, 6.496282

In [ ]:
y2 = getlabel(newdata_t_al, model)

torch.Size([100, 7])
tensor([3, 2, 3, 0, 2, 6, 5, 3, 0, 2, 6, 3, 2, 3, 5, 4, 2, 6, 6, 4, 2, 6, 5, 4,
        0, 2, 6, 6, 5, 1, 3, 2, 1, 3, 2, 0, 0, 1, 1, 2, 6, 6, 5, 6, 1, 3, 0, 3,
        4, 6, 2, 5, 3, 3, 2, 0, 0, 5, 6, 0, 1, 1, 2, 1, 2, 1, 6, 6, 1, 5, 3, 6,
        2, 6, 0, 3, 5, 4, 5, 4, 0, 1, 6, 1, 3, 2, 3, 1, 1, 6, 2, 6, 2, 1, 6, 6,
        4, 6, 6, 4])


In [ ]:
df_al['label'] = y2
df_al

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Unnamed: 0                                             nopunc  \
64          627  中国 射击队 总教练 张福 我国 射击 健儿 将 在 第十届 亚运会 上 参加 十五个 项目...   
588       11337  新华社 二十八日 讯 人大常委会 副委员长 郭沫若 今天上午 接见 了 以 羽根 荣一 为首...   
585       23153  我队 以三比 击败 西德 队据 新华社 卢布尔雅那 十七日 电 第二十八届 世界 乒乓球 锦...   
580       10930  本报记者 张志文 俞懿春 陈然 为期 两天 的 海洋 争端 解决 国际法 研讨会 月 日 在...   
977       15512  自杀 已 成为 导致 日本 国家 公务员 死亡 的 第二 大 杀手 这是 日本 人事 院对 ...   
..          ...                                                ...   
946       26878  本报记者 刘仲华 赵成 李锋曲 翔宇 月 日 上午 国家 主席 习近平 应邀出席 在 巴布亚...   
738        9349  本报记者 董洪亮 对 城乡 公办 小学 初中 实行 标准化 建设 这是 一个 重要 的 转折...   
485       27606  读 世界 园林 发展 概论 顾孟潮 当 中国 城市化 进程 空前 加速 许多 城市 把 建设...   
793       12773  张岂之 中国 社会 与 西方 文化 这是 一个 值得 研究 的 大 课题 吉林大学 宝成关 ...   
564       10294  新华社 北京 月 日电 中国国际贸易促进委员会 主任 王耀庭 今天 晚上 在 人民大会堂 举...   

                                                 score  \
64   [0.03281145845671823, -0.017463615092265815, -...   
588  [0.29648743156719615, 0.32386012075554876, 0.1...   
585  [-0.08030344345551038, 0.21372191697900417, -0...   
580  [0.0788475778882582, 0.04253629233204423, -0.0...   
977  [0.6826887657522522, -0.019241865926012004, 0....   
..                                                 ...   
946  [0.12110538111962316, -0.022792907240132772, 0...   
738  [0.07226085488766978, 0.0029080748422330265, -...   
485  [-0.006193101111100044, 0.07028134702255641, 0...   
793  [-0.01797448345831555, 0.014464619837890713, -...   
564  [0.3168834037615782, 0.20495370786071576, 0.12...   

                                                  ids2  label  cluster_db  
64   [0.0005638877, 0.0008500327, 0.00076776685, 0....      3          35  
588  [0.00044431264, 0.0006750464, 0.00052068726, 0...      2         490  
585  [0.00048121772, 0.0007018915, 0.0006014369, 0....      3         724  
580  [0.00047915656, 0.0007838957, 0.0007558922, 0....      0         479  
977  [0.0004532733, 0.0006645717, 0.00050379726, 0....      2         606  
..                                                 ...    ...         ...  
946  [0.0004722344, 0.0007055999, 0.0005853253, 0.0...      6         447  
738  [0.0004892258, 0.00074898213, 0.0007000114, 0....      4         273  
485  [0.0005228274, 0.00079466746, 0.0007758035, 0....      6         520  
793  [0.0004754468, 0.00074939243, 0.00064402405, 0...      6         122  
564  [0.00046765327, 0.00072707055, 0.00052286556, ...      4         457  

[100 rows x 6 columns]

In [ ]:
#保存该数据
df_al.to_csv("/content/drive/MyDrive/第四轮验证集主动学习数据/al_0708_new.csv", index=False)

##### 在原始的数据集中去掉筛选出来的数据

In [ ]:
ind_old = df_al['Unnamed: 0']
ind_old

64       627
588    11337
585    23153
580    10930
977    15512
       ...  
946    26878
738     9349
485    27606
793    12773
564    10294
Name: Unnamed: 0, Length: 100, dtype: int64

In [ ]:
df_new = df.drop(index=ind_old)
df_new

Unnamed: 0                                             nopunc  \
0               0  一九六九年 四月 一日 报告 四月 十四日 通过 林彪 同志 们 中国共产党第九次全国代表大...   
1               1  三月份 月度 进出口 规模 创新 高 本报 北京 月 日 讯 记者 杜 海涛 报道 海关 最...   
2               2  上海 石油化工 总厂 靠 智力开发 起飞 本报记者 吴复民 红玛瑙 似的 运转 指示灯 蓦然...   
3               3  下关市 举行宴会 欢迎 廖承志 副委员长 一行 据 新华社 下关 五月 九日 电以 廖承志 ...   
4               4  世界 人民 和平 大会 记事 袁水拍 和平 运动 的 老战士 们 像 意大利 多尼 尼 教授...   
...           ...                                                ...   
29834       29834  马巍年 中国 电影 市场 春节 档 创造 了 新 的 纪录 得益于 多部 本土 贺岁 新片 ...   
29835       29835  马本斋 抗日战争 时期 在 华北平原 上 活跃 着 一支 以 回民 兄弟 为主 组成 的 抗...   
29836       29836  黄国越 强烈 谴责 美机 轰炸 北方 的 强盗 罪行 强调 越南 南北方 人民 决心 战胜 ...   
29837       29837  黑脸 琵鹭 请 让 我 来 关心 你 本报记者 钟嘉 严寒 挡不住 野生动物 保护者 们 的...   
29838       29838  齐晖 回到 正常 轨道 据 新华社 北京 月 日电 记者 杨 金志 张薇 好运 北京 中国 ...   

                                                   score  \
0      [0.03160141239429076, -0.04957382465915392, -0...   
1      [0.04964349019864235, 0.10936169526692757, 0.2...   
2      [0.08104942550423407, 0.13883518507868425, 0.0...   
3      [-0.0023794892647571574, 0.07346247383454761, ...   
4      [-0.02011695787621593, 0.055439573707884174, 0...   
...                                                  ...   
29834  [0.01587601603410936, 0.03764139184979351, 0.0...   
29835  [0.09842621728702378, 0.012364107498986858, 0....   
29836  [0.008617210604590055, -0.010541628111763762, ...   
29837  [-0.13765827980058357, 0.21133572460376754, -0...   
29838  [-0.09221178504979227, 0.04223222883799189, 0....   

                                                    ids2  label  cluster_db  
0      [0.00048361006, 0.0007332484, 0.0007011582, 0....      6          -1  
1      [0.00047500295, 0.0006828284, 0.0005490131, 0....      5          -1  
2      [0.00047698742, 0.00074580207, 0.00063491095, ...      6           0  
3      [0.00051801256, 0.000820847, 0.00079044106, 0....      1          -1  
4      [0.00050378207, 0.0008450187, 0.000899082, 0.0...      4          -1  
...                                                  ...    ...         ...  
29834  [0.00047775434, 0.00074808166, 0.00064183446, ...      6         111  
29835  [0.00050345284, 0.0008048199, 0.00074749044, 0...      5          -1  
29836  [0.00050013704, 0.00077063765, 0.0007441554, 0...      5          -1  
29837  [0.00048234698, 0.0007665205, 0.0007214704, 0....      5          -1  
29838  [0.0004863677, 0.0007542312, 0.00069294375, 0....      5          -1  

[29739 rows x 6 columns]

In [ ]:
#将新的数据保存，可以保存为原来的名字，也可以保存为新文件，但是保存为新文件的话，下次再开头读入数据的时候就要改为新的文件地址
df_new.to_csv("/content/drive/MyDrive/Colab Notebooks/情感轨道打分数据/0705_all_7cluster_3_4_第san版.csv", index=False)